# Generated by Django 5.1.1 on 2025-03-23 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created_at_post_description_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='purchase',
            field=models.ManyToManyField(blank=True, related_name='purchased_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
